export const BRAND = {
  name: 'ManiKunj',
  tagline: 'Wear Your Story — Cotton-On Inspired Fashion for India & Beyond',
  description: 'ManiKunj — Premium Cotton On-style fashion for Women, Men & Kids. Trend-led essentials, relaxed fits, joyful everyday wear. Fully CMS-driven, rebrandable platform.',
  companyLegal: 'ManiKunj Fashion Pvt Ltd',
  supportEmail: 'hello@manikunj.com',
  supportPhone: '+91 98765 43210',
  address: 'MG Road, Bangalore, Karnataka 560001, India',
  currency: 'INR',
  currencySymbol: '₹',
  locale: 'en-IN',
  colors: {
    primary: '#111111',
    primaryDark: '#000000',
    secondary: '#111111',
    accent: '#ff4d6d',
    accentDark: '#e6003a',
    background: '#ffffff',
    surface: '#ffffff',
    text: '#111111',
    muted: '#6b7280',
    border: '#e5e7eb',
    success: '#16a34a',
    warning: '#f59e0b',
    error: '#e6003a',
    special: '#ff4d6d',
    halfPrice: '#e6003a',
    announcement: '#ff4d6d',
    sale: '#e6003a',
  },
  fonts: {
    heading: '"Space Grotesk", "Helvetica Neue", Arial, sans-serif',
    body: '"Inter", "Helvetica Neue", Arial, sans-serif',
  },
  logo: '/manikunj-logo.svg',
  favicon: '/favicon.ico',
  social: {
    instagram: 'https://instagram.com/manikunj',
    facebook: 'https://facebook.com/manikunj',
    tiktok: 'https://tiktok.com/@manikunj',
  },
} as const;
