// India Master Taxonomy — Instamart-style depth — comprehensive
export const INDIA_DEPARTMENTS = [
  { id:'in_fresh_veg', slug:'fresh-vegetables', name:'Fresh Vegetables', icon:'🥦' },
  { id:'in_fresh_fruits', slug:'fresh-fruits', name:'Fresh Fruits', icon:'🍎' },
  { id:'in_dairy', slug:'dairy-bread-eggs', name:'Dairy, Bread & Eggs', icon:'🥛' },
  { id:'in_meat', slug:'meat-seafood', name:'Meat & Seafood', icon:'🍗' },
  { id:'in_atta_rice_dal', slug:'atta-rice-dal', name:'Atta, Rice & Dal', icon:'🌾' },
  { id:'in_masala', slug:'masalas-cooking', name:'Masalas & Cooking Essentials', icon:'🌶️' },
  { id:'in_oil', slug:'oils-ghee', name:'Oils & Ghee', icon:'🫒' },
  { id:'in_cereals', slug:'cereals-breakfast', name:'Cereals & Breakfast', icon:'🥣' },
  { id:'in_munchies', slug:'munchies', name:'Munchies', icon:'🥨' },
  { id:'in_biscuits', slug:'biscuits-cakes', name:'Biscuits & Cakes', icon:'🍪' },
  { id:'in_sweet', slug:'sweet-tooth', name:'Sweet Tooth', icon:'🍫' },
  { id:'in_cold_drinks', slug:'cold-drinks-juices', name:'Cold Drinks & Juices', icon:'🥤' },
  { id:'in_tea_coffee', slug:'tea-coffee-more', name:'Tea, Coffee & More', icon:'☕' },
  { id:'in_noodles', slug:'noodles-pasta', name:'Noodles, Pasta & Vermicelli', icon:'🍜' },
  { id:'in_instant', slug:'instant-frozen', name:'Instant & Frozen Food', icon:'❄️' },
  { id:'in_sauces', slug:'sauces-spreads', name:'Sauces & Spreads', icon:'🍅' },
  { id:'in_cleaning', slug:'cleaning-essentials', name:'Cleaning Essentials', icon:'🧹' },
  { id:'in_bath', slug:'bath-body-hair', name:'Bath, Body & Hair', icon:'🧴' },
  { id:'in_beauty', slug:'beauty-grooming', name:'Beauty & Grooming', icon:'💄' },
  { id:'in_baby', slug:'baby-care', name:'Baby Care', icon:'👶' },
  { id:'in_pet', slug:'pet-supplies', name:'Pet Supplies', icon:'🐾' },
  { id:'in_home', slug:'home-kitchen', name:'Home & Kitchen', icon:'🏠' },
  { id:'in_pooja', slug:'pooja-festive', name:'Pooja & Festive', icon:'🪔' },
  { id:'in_regional', slug:'regional-india', name:'Regional India', icon:'🗺️' },
  // keep legacy for compat
  { id:'in_staples', slug:'staples', name:'Atta, Flour & Sooji (Legacy)', icon:'🌾' },
  { id:'in_rice', slug:'rice', name:'Rice (Legacy)', icon:'🍚' },
  { id:'in_dal', slug:'dal-pulses', name:'Dal & Pulses (Legacy)', icon:'🫘' },
  { id:'in_beverages', slug:'beverages', name:'Beverages (Legacy)', icon:'🥤' },
  { id:'in_frozen', slug:'frozen-foods', name:'Frozen (Legacy)', icon:'❄️' },
  { id:'in_personal', slug:'personal-care', name:'Personal Care (Legacy)', icon:'🧴' },
  { id:'in_organic', slug:'organic', name:'Organic (Legacy)', icon:'🌱' },
] as const;

export const INDIA_CATEGORIES: { id:string; departmentId:string; slug:string; name:string }[] = [
  // Fresh Veg
  { id:'cat_fresh_veg', departmentId:'in_fresh_veg', slug:'fresh-vegetables', name:'Fresh Vegetables' },
  { id:'cat_leafy', departmentId:'in_fresh_veg', slug:'leafy-seasonings', name:'Leafy Vegetables & Seasonings' },
  { id:'cat_exotic_veg', departmentId:'in_fresh_veg', slug:'exotic-vegetables', name:'Exotic Vegetables' },
  { id:'cat_organic_veg', departmentId:'in_fresh_veg', slug:'organic-vegetables', name:'Organic Vegetables' },
  { id:'cat_cuts_sprouts', departmentId:'in_fresh_veg', slug:'cuts-sprouts', name:'Cuts & Sprouts' },
  { id:'cat_frozen_veg', departmentId:'in_fresh_veg', slug:'frozen-vegetables', name:'Frozen Vegetables' },
  { id:'cat_herbs', departmentId:'in_fresh_veg', slug:'fresh-herbs', name:'Fresh Herbs' },
  { id:'cat_onion_potato', departmentId:'in_fresh_veg', slug:'onions-potatoes', name:'Onions & Potatoes' },
  { id:'cat_chillies', departmentId:'in_fresh_veg', slug:'chillies', name:'Chillies' },
  // Fresh Fruits
  { id:'cat_fresh_fruits', departmentId:'in_fresh_fruits', slug:'fresh-fruits', name:'Fresh Fruits' },
  { id:'cat_bananas', departmentId:'in_fresh_fruits', slug:'bananas', name:'Bananas' },
  { id:'cat_apples', departmentId:'in_fresh_fruits', slug:'apples', name:'Apples' },
  { id:'cat_mangoes', departmentId:'in_fresh_fruits', slug:'mangoes', name:'Mangoes' },
  { id:'cat_exotic_fruits', departmentId:'in_fresh_fruits', slug:'exotic-fruits', name:'Exotic Fruits' },
  { id:'cat_cut_fruits', departmentId:'in_fresh_fruits', slug:'cut-fruits', name:'Cut Fruits' },
  // Dairy
  { id:'cat_milk', departmentId:'in_dairy', slug:'milk', name:'Milk' },
  { id:'cat_bread', departmentId:'in_dairy', slug:'bread-buns', name:'Bread & Buns' },
  { id:'cat_paneer', departmentId:'in_dairy', slug:'paneer-tofu', name:'Paneer & Tofu' },
  { id:'cat_cheese', departmentId:'in_dairy', slug:'cheese', name:'Cheese' },
  { id:'cat_curd', departmentId:'in_dairy', slug:'curd-yogurt', name:'Curd & Yogurt' },
  { id:'cat_eggs', departmentId:'in_dairy', slug:'eggs', name:'Eggs' },
  // Meat
  { id:'cat_chicken_curry', departmentId:'in_meat', slug:'chicken-curry-cut', name:'Chicken Curry Cut' },
  { id:'cat_chicken_breast', departmentId:'in_meat', slug:'chicken-breast', name:'Chicken Breast' },
  { id:'cat_mutton', departmentId:'in_meat', slug:'mutton-curry-cut', name:'Mutton Curry Cut' },
  { id:'cat_fish', departmentId:'in_meat', slug:'fish', name:'Fish' },
  { id:'cat_prawns', departmentId:'in_meat', slug:'prawns', name:'Prawns' },
  // Atta Rice Dal
  { id:'cat_atta', departmentId:'in_atta_rice_dal', slug:'wheat-atta', name:'Wheat Atta' },
  { id:'cat_atta_multi', departmentId:'in_atta_rice_dal', slug:'multigrain-atta', name:'Multigrain Atta' },
  { id:'cat_rice_basmati', departmentId:'in_atta_rice_dal', slug:'basmati-rice', name:'Basmati Rice' },
  { id:'cat_toor', departmentId:'in_atta_rice_dal', slug:'toor-dal', name:'Toor Dal' },
  { id:'cat_moong', departmentId:'in_atta_rice_dal', slug:'moong-dal', name:'Moong Dal' },
  { id:'cat_urad', departmentId:'in_atta_rice_dal', slug:'urad-dal', name:'Urad Dal' },
  { id:'cat_besan', departmentId:'in_atta_rice_dal', slug:'besan', name:'Besan' },
  { id:'cat_sooji', departmentId:'in_atta_rice_dal', slug:'sooji-rava', name:'Sooji/Rava' },
  { id:'cat_millets', departmentId:'in_atta_rice_dal', slug:'millets', name:'Millets' },
  // Masala
  { id:'cat_powdered_spices', departmentId:'in_masala', slug:'powdered-spices', name:'Powdered Spices' },
  { id:'cat_whole_spices', departmentId:'in_masala', slug:'whole-spices', name:'Whole Spices' },
  { id:'cat_garam_masala', departmentId:'in_masala', slug:'garam-masala', name:'Garam Masala' },
  { id:'cat_salt', departmentId:'in_masala', slug:'salt', name:'Salt' },
  { id:'cat_jaggery', departmentId:'in_masala', slug:'jaggery', name:'Jaggery' },
  { id:'cat_pickle', departmentId:'in_masala', slug:'pickles', name:'Pickles' },
  // Oils
  { id:'cat_sunflower', departmentId:'in_oil', slug:'sunflower-oil', name:'Sunflower Oil' },
  { id:'cat_mustard_oil', departmentId:'in_oil', slug:'mustard-oil', name:'Mustard Oil' },
  { id:'cat_ghee', departmentId:'in_oil', slug:'ghee', name:'Ghee' },
  { id:'cat_coconut_oil', departmentId:'in_oil', slug:'coconut-oil', name:'Coconut Oil' },
  // Cereals
  { id:'cat_oats', departmentId:'in_cereals', slug:'oats', name:'Oats' },
  { id:'cat_muesli', departmentId:'in_cereals', slug:'muesli', name:'Muesli' },
  { id:'cat_cornflakes', departmentId:'in_cereals', slug:'corn-flakes', name:'Corn Flakes' },
  { id:'cat_peanut_butter', departmentId:'in_cereals', slug:'peanut-butter', name:'Peanut Butter' },
  { id:'cat_honey', departmentId:'in_cereals', slug:'honey', name:'Honey' },
  // Munchies
  { id:'cat_chips', departmentId:'in_munchies', slug:'chips-crisps', name:'Chips & Crisps' },
  { id:'cat_bhujia', departmentId:'in_munchies', slug:'bhujia', name:'Bhujia' },
  { id:'cat_namkeen', departmentId:'in_munchies', slug:'namkeen', name:'Namkeen' },
  { id:'cat_nuts', departmentId:'in_munchies', slug:'nuts', name:'Nuts' },
  { id:'cat_makhana', departmentId:'in_munchies', slug:'makhana', name:'Makhana' },
  // Biscuits
  { id:'cat_cookies', departmentId:'in_biscuits', slug:'cookies', name:'Cookies' },
  { id:'cat_cream_biscuit', departmentId:'in_biscuits', slug:'cream-biscuits', name:'Cream Biscuits' },
  { id:'cat_rusk', departmentId:'in_biscuits', slug:'rusk', name:'Rusk' },
  // Sweet
  { id:'cat_chocolate_bar', departmentId:'in_sweet', slug:'chocolate-bars', name:'Chocolate Bars' },
  { id:'cat_ice_cream_tub', departmentId:'in_sweet', slug:'ice-cream-tubs', name:'Ice Cream Tubs' },
  // Cold drinks
  { id:'cat_cola', departmentId:'in_cold_drinks', slug:'cola', name:'Cola' },
  { id:'cat_juices', departmentId:'in_cold_drinks', slug:'juices', name:'Juices' },
  { id:'cat_coconut_water', departmentId:'in_cold_drinks', slug:'coconut-water', name:'Coconut Water' },
  // Tea Coffee
  { id:'cat_black_tea', departmentId:'in_tea_coffee', slug:'black-tea', name:'Black Tea' },
  { id:'cat_green_tea', departmentId:'in_tea_coffee', slug:'green-tea', name:'Green Tea' },
  { id:'cat_instant_coffee', departmentId:'in_tea_coffee', slug:'instant-coffee', name:'Instant Coffee' },
  { id:'cat_protein', departmentId:'in_tea_coffee', slug:'protein-powders', name:'Protein Powders' },
  // Noodles
  { id:'cat_instant_noodles', departmentId:'in_noodles', slug:'instant-noodles', name:'Instant Noodles' },
  { id:'cat_pasta', departmentId:'in_noodles', slug:'pasta', name:'Cooking Pasta' },
  // Cleaning
  { id:'cat_detergent_powder', departmentId:'in_cleaning', slug:'detergent-powder', name:'Detergent Powder' },
  { id:'cat_dishwash', departmentId:'in_cleaning', slug:'dishwashing', name:'Dishwashing' },
  { id:'cat_floor_cleaner', departmentId:'in_cleaning', slug:'floor-cleaners', name:'Floor Cleaners' },
  // Bath
  { id:'cat_shampoo', departmentId:'in_bath', slug:'shampoo', name:'Shampoo' },
  { id:'cat_soap', departmentId:'in_bath', slug:'soap', name:'Soap' },
  { id:'cat_face_wash', departmentId:'in_bath', slug:'face-wash', name:'Face Wash' },
  // Beauty
  { id:'cat_lipstick', departmentId:'in_beauty', slug:'lipstick', name:'Lipstick' },
  // Baby
  { id:'cat_diapers', departmentId:'in_baby', slug:'diapers', name:'Diapers' },
  { id:'cat_baby_food', departmentId:'in_baby', slug:'baby-food', name:'Baby Food' },
  // Pet
  { id:'cat_dog_food', departmentId:'in_pet', slug:'dog-food', name:'Dog Food' },
  { id:'cat_cat_food', departmentId:'in_pet', slug:'cat-food', name:'Cat Food' },
  // Home
  { id:'cat_kitchen_tools', departmentId:'in_home', slug:'kitchen-tools', name:'Kitchen Tools' },
  { id:'cat_pooja_needs', departmentId:'in_pooja', slug:'pooja-needs', name:'Pooja Needs' },
  { id:'cat_agarbatti', departmentId:'in_pooja', slug:'agarbatti', name:'Agarbatti' },
  // Regional
  { id:'cat_north_indian', departmentId:'in_regional', slug:'north-indian', name:'North Indian' },
  { id:'cat_south_indian', departmentId:'in_regional', slug:'south-indian', name:'South Indian' },
  // Legacy aliases for compat
  { id:'cat_maida', departmentId:'in_staples', slug:'maida-sooji-legacy', name:'Maida & Sooji (Legacy)' },
  { id:'cat_rice_other', departmentId:'in_rice', slug:'other-rice-legacy', name:'Other Rice (Legacy)' },
  { id:'cat_chana_dal', departmentId:'in_dal', slug:'chana-dal-legacy', name:'Chana Dal (Legacy)' },
  { id:'cat_tea', departmentId:'in_tea_coffee', slug:'tea-legacy', name:'Tea (Legacy)' },
  { id:'cat_coffee', departmentId:'in_tea_coffee', slug:'coffee-legacy', name:'Coffee (Legacy)' },
  { id:'cat_soft_drinks', departmentId:'in_beverages', slug:'soft-drinks-legacy', name:'Soft Drinks (Legacy)' },
  { id:'cat_hair', departmentId:'in_personal', slug:'hair-care-legacy', name:'Hair Care (Legacy)' },
  { id:'cat_oral', departmentId:'in_personal', slug:'oral-care-legacy', name:'Oral Care (Legacy)' },
];

export const SOURCE_CATEGORY_MAPPING: Record<string, string> = {
  'Atta':'Atta, Rice & Dal → Wheat Atta',
  'Flour':'Atta, Rice & Dal → Wheat Atta',
  'Atta & Flour':'Atta, Rice & Dal → Wheat Atta',
  'Curd & Yogurt':'Dairy, Bread & Eggs → Curd & Yogurt',
  'Curd and Yogurts':'Dairy, Bread & Eggs → Curd & Yogurt',
  'Yogurt & Curd':'Dairy, Bread & Eggs → Curd & Yogurt',
  'Coca Cola':'Beverages → Soft Drinks',
  'Coca-Cola':'Beverages → Soft Drinks',
  'COCA COLA':'Beverages → Soft Drinks',
};

export const PRODUCT_ALIASES: Record<string,string[]> = {
  'atta':['flour','maida'],
  'dal':['daal','dhal'],
  'dahi':['curd','yogurt'],
  'curd':['dahi','yogurt'],
  'sooji':['suji','rava','semolina'],
  'suji':['sooji','rava','semolina'],
  'rava':['sooji','suji','semolina'],
  'besan':['gram flour'],
  'poha':['flattened rice','aval'],
  'chana':['chana dal','chickpea','kabuli chana'],
  'rajma':['kidney bean'],
  'sabudana':['sago'],
  'dhania':['coriander','dhaniya'],
  'jeera':['cumin'],
  'haldi':['turmeric'],
  'mirchi':['chilli','mirch'],
  'pyaaz':['onion'],
  'aloo':['potato'],
  'bhindi':['okra','ladyfinger'],
  'lauki':['bottle gourd','ghiya'],
  'baingan':['brinjal','eggplant'],
  'ragi':['finger millet','nachni'],
  'sarson oil':['mustard oil'],
  'mustard oil':['sarson oil'],
};
